* Updating with what's working
git-svn-id: https://the.narro.ws/svn/brimstone/openwrt/brim-mesh@717 9fd2b4f7-785e-4997-ad42-798039e1f157

diff --git a/files/nodeadm b/files/nodeadm
--- a/files/nodeadm
+++ b/files/nodeadm
@@ -48,6 +48,7 @@ gatewaymode() {
 		/etc/init.d/dnsmasq start
 	fi
 	isrunning dnsmasq || /etc/init.d/dnsmasq start
+	/etc/init.d/nodogsplash start
 }
 
 standalonemode() {
@@ -55,12 +56,11 @@ standalonemode() {
 	batctl gw server
 	logit "now a server"
 	# start handing out IPs
-	# dnsmasq cannot be running when splashd starts. It looks up something, then fucks up everything
 	/etc/init.d/dnsmasq stop
-	/etc/init.d/splashd start
 	# we don't know anything, so become everything!
 	echo "address=/#/1.1.1.1" > /etc/dnsmasq.conf
 	/etc/init.d/dnsmasq start
+	/etc/init.d/nodogsplash start
 	ifconfig eth0 192.168.0.2
 	route add default gw 192.168.0.1
 }
@@ -68,19 +68,124 @@ standalonemode() {
 clientmode() {
 	blink
 	batctl gw client
+	/etc/init.d/dnsmasq stop
+	/etc/init.d/nodogsplash stop
 	logit "now a client"
 }
 
+config() {
+### Main radio0 will broadcast one AP with no encryption 
+### Another VAP in adhoc mode is added to main radio0.
+
+### Node-specific settings
+read -p "Hostname: " HOSTNAME
+read -p "IP: " IP
+
+### These parameters should be consistent across all nodes
+export NETMASK="255.255.252.0" 
+export DNS="" 
+export GATEWAY="" 
+export PUBLIC_ESSID="The Mesh"
+export PUBLIC_BSSID="DE:AD:BE:EF:CA:FE"
+export ADHOC0_BSSID="CA:CA:CA:CA:CA:00" 
+export ADHOC0_ESSID="meshtrunk"
+export ADHOC0_CHANNEL="1" 
+
+### Ensure of populating /etc/config/wireless with 
+### autodetected wifi-device entries (radioX)
+### to get all list_capab and hwmode correct. Otherwise
+### OpenWRT might fail to configure the radio properly.
+wifi detect >>/etc/config/wireless
+
+### Clear preexisting wifi-iface sections to avoid conflicts or dups
+( for i in `seq 0 9` ; do echo "delete wireless.@wifi-iface[]" ; done ) | uci batch -q
+
+### Create /etc/config/batman-adv if it's not there yet.
+uci import -m batman-adv </dev/null
+
+echo " 
+set system.@system[0].hostname=$HOSTNAME
+set dhcp.@dnsmasq[0].domain=mesh
+
+set batman-adv.bat0=mesh
+set batman-adv.bat0.gw_mode=client
+
+delete network.wan
+set network.wan=interface
+set network.wan.ifname=eth0
+set network.wan.proto=dhcp
+set network.lan.ipaddr=$IP
+set network.lan.netmask=$NETMASK
+set network.lan.dns='$DNS'
+set network.lan.gateway=$GATEWAY
+set network.lan.ifname='bat0'
+set network.mesh=interface
+set network.mesh.ifname=adhoc0
+set network.mesh.proto=batadv
+set network.mesh.mtu=1528
+set network.mesh.mesh=bat0
+
+set wireless.radio0=wifi-device
+set wireless.radio0.channel=$ADHOC0_CHANNEL
+set wireless.radio0.disabled=0
+set wireless.radio0.phy=phy0
+set wireless.radio0.macaddr=
+
+add wireless wifi-iface
+set wireless.@wifi-iface[-1].device=radio0
+set wireless.@wifi-iface[-1].encryption=none
+set wireless.@wifi-iface[-1].network=lan
+set wireless.@wifi-iface[-1].mode=ap
+set wireless.@wifi-iface[-1].ssid='$PUBLIC_ESSID'
+set wireless.@wifi-iface[-1].bssid=$PUBLIC_BSSID
+
+add wireless wifi-iface
+set wireless.@wifi-iface[-1].device=radio0 
+set wireless.@wifi-iface[-1].ifname=adhoc0
+set wireless.@wifi-iface[-1].encryption=none
+set wireless.@wifi-iface[-1].network=mesh
+set wireless.@wifi-iface[-1].mode=adhoc 
+set wireless.@wifi-iface[-1].bssid=$ADHOC0_BSSID
+set wireless.@wifi-iface[-1].ssid='$ADHOC0_ESSID'
+set wireless.@wifi-iface[-1].mcast_rate=11000 
+set wireless.@wifi-iface[-1].hidden=true
+
+commit" \
+| uci batch
+}
+
+if [ "$1" = "check" ]; then
+
+MYNET="$(ip -o addr show dev br-lan | awk '/inet / {print $4}')"
+MYIP="${MYNET%%/*}"
 if ! isrouting; then
 	# set iptables rules
 	iptables -t nat -F POSTROUTING
-	iptables -t nat -A POSTROUTING -s $(ip -o addr show dev br-lan | awk '/inet / {print $4}') -j MASQUERADE
+	iptables -t nat -A POSTROUTING -s $MYNET -j MASQUERADE
 	# set kernel forwarder
 	echo 1 > /proc/sys/net/ipv4/ip_forward
 	logit "Setting up routing"
 fi
 
-if [ "$1" = "check" ]; then
+if ! grep -q "$MYIP" /etc/nodogsplash/nodogsplash.conf; then
+	sed -i "/FirewallRuleSet preauthenticated-users/ a FirewallRule allow tcp port 80 to $MYIP" /etc/nodogsplash/nodogsplash.conf
+	/etc/init.d/nodogsplash stop
+	/etc/init.d/nodogsplash start
+fi
+
+HOST="$(uci get system.@system[0].hostname)"
+if ! grep -q "$HOST" /etc/nodogsplash/htdocs/splash.html; then
+	cat << dog > /etc/nodogsplash/htdocs/splash.html
+<html>
+<head>
+<meta http-equiv="refresh" content="0;URL='http://$HOST.mesh/'">
+</head>
+<body>
+</body>
+</html>
+dog
+fi
+
 # if we have a link
 if ! nolink; then
 	logit "has a link"
@@ -139,6 +244,8 @@ elif [ "$1" = "mode" ]; then
 	fi
 	echo "Unknown"
 	exit
+elif [ "$1" = "config" ]; then
+	config
 else
-	echo "Usage: $0 <check|gateway|standalone|client|mode>"
+	echo "Usage: $0 <check|gateway|standalone|client|mode|config>"
 fi
